version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: testuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"  # Host port: 3307, Container port: 3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  my-spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8081:8080"  # Host port: 8081, Container port: 8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
